### PR TITLE
Local Cache Saves

### LINKED ISSUE #10: Local Cache Saves

### PR DESCRIPTION
**Pull request by MuddyHope**
Using a local json file to save previous searches so, it will be easier to fetch previously accessed success paths.

This solves Issue: https://github.com/ArchooD2/KevinBacon/issues/10

### CODE REVIEW

**Comment by ArchooD2** [comment]
Testing this really quick on my hardware, hoping to learn to make tests soon to automate that via Github Actions.

**Comment by MuddyHope** [comment]
Would suggest pytest with black.

**Comment by MuddyHope** [comment]
> Testing this really quick on my hardware, hoping to learn to make tests soon to automate that via Github Actions.

**Comment by MuddyHope** [comment]
https://github.com/bors-ng/bors-ng

We can use this for merging.

**Comment by ArchooD2** [comment]
I rabbitholed when I read "pytest with black"

**Comment by ArchooD2** [comment]
note: rabbitholed in this context is me not knowing what that was and getting lost on google

**Comment by ArchooD2** [comment]
LGTM, Merging unless you have any objections. After this, will set up github actions stuff

**Comment by MuddyHope** [comment]
No issues from myside. Thanks.

**Pull request merged**
